version: '3'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      